config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'master#home'

  get 'help', to: 'master#help'
  get 'about', to: 'master#about'
  get 'contact', to: 'master#contact'

  resources :users, only: %i[index show destroy] do
    resources :following, only: :index
    resources :followers, only: :index
  end

  resources :posts do
    resources :comments
  end

  resources :comments do
    resources :comments
  end

  resources :relationships, only: %i[create destroy]
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  admin                  :boolean          default(FALSE)
#  confirmation_sent_at   :datetime
#  confirmation_token     :string
#  confirmed_at           :datetime
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  failed_attempts        :integer          default(0), not null
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :string
#  locked_at              :datetime
#  name                   :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  sign_in_count          :integer          default(0), not null
#  unconfirmed_email      :string
#  unlock_token           :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_confirmation_token    (confirmation_token) UNIQUE
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_unlock_token          (unlock_token) UNIQUE
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # devise :database_authenticatable, :registerable,
  #   :recoverable, :rememberable, :trackable, :validatable,
  #   :confirmable, :lockable, :timeoutable
  #   :confirmable, :lockable, :timeoutable, :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :timeoutable

  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: 'follower_id',
                                  inverse_of: :follower,
                                  dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: 'followed_id',
                                   inverse_of: :followed,
                                   dependent: :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Post.where(
      "user_id IN (#{following_ids})
      OR user_id = :user_id", user_id: id
    )
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[index destroy]
  before_action :admin_user, only: :destroy
  before_action :find_user, only: %i[show destroy]

  def index
    @users = User.paginate page: params[:page], per_page: 10
  end

  def show
    @posts = @user.posts.paginate page: params[:page], per_page: 10
    @postpage = true
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html do
        flash[:success] = 'User deleted'
        redirect_back fallback_location: root_path
      end
      format.js do
        render file: 'users/destroy.js.erb'
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :name, :email, :password, :password_confirmation
    )
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  def find_user
    @user = User.find_by id: params[:id]
    return if @user

    redirect_to root_url, flash: { danger: 'User not found' }
  end
end

app/views/users/_follow.html.erb
<%= form_for(
  current_user.active_relationships.build,
  remote: true
) do |f| %>
<div>
  <%= hidden_field_tag :followed_id, @user.id %>
</div>
<%= f.submit "Follow",
  class: "btn btn-outline-primary btn-sm"
%>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <span id="follow_form" style="display: inline-block;">
    <% if current_user.following?(@user) %>
      <%= render "users/unfollow" %>
    <% else %>
      <%= render "users/follow" %>
    <% end %>
  </span>
<% end %>

app/views/users/_form.html.erb
<div class="container-fluid py-3">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <fieldset>
          <div class="form-group">
            <%= f.text_field :name,
              id: :name,
              class: "form-control input-lg",
              placeholder: 'Your name' %>
          </div>
          <div class="form-group">
            <%= f.email_field :email,
              id: :email,
              class: "form-control input-lg",
              placeholder: 'name@domain.com' %>
          </div>
          <div class="form-group">
            <%= f.password_field :password,
              id: :password,
              class: "form-control input-lg",
              placeholder: 'Password' %>
          </div>
          <div class="form-group">
            <%= f.password_field :password_confirmation,
              id: :password_confirmation,
              class: "form-control input-lg",
              placeholder: 'Password confirmation' %>
          </div>
          <%= f.submit yield(:button_text),
            class: "btn btn-lg btn-primary btn-block" %>
        </fieldset>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<a href="<%= user_following_index_path(@user) %>">
  <span class="badge badge-primary" id="following">
    <%= @user.following.count %>
  </span>
  following
</a>
<a href="<%= user_followers_path(@user) %>">
  <span
   class="badge badge-primary"
   id="followers">
    <%= @user.followers.count %>
  </span>
  followers
</a>

app/views/users/_unfollow.html.erb
<%= form_for(
  current_user.active_relationships.find_by(
    followed_id: @user.id
  ),
  html: {
    method: :delete
  },
  remote: true
) do |f| %>
<%= f.submit "Unfollow", class: "btn btn-outline-secondary btn-sm" %>
<% end %>

app/views/users/_user.html.erb
<li class="list-group-item" id="user-<%= user.id %>">
  <%= link_to user.name, user_path(user) %>
  <% if user.admin? %>
    <span class="badge badge-success">admin</span>
  <% end %>
  <% if user_signed_in? && current_user.admin? && !current_user?(user) %>
    <%= link_to "delete",
      user,
      method: :delete,
      data: {
        confirm: "Delete the user?"
      },
      class: "btn btn-outline-danger btn-sm delete_user",
      remote: true
    %>
<% end %>
</li>

app/views/users/destroy.js.erb
$("#user-<%= @user.id %>").remove();

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<div class="col-md-12 mx-auto">
  <ul class="list-group list-group-flush">
    <%= render partial: 'user', collection: @users %>
    <%= will_paginate(
      @users,
      renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer
    ) %>
  </ul>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="col-md-3">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">
        <%= @user.name %>
        <% if @user.admin? %>
          <span class="badge badge-success">admin</span>
        <% end %>
      </h5>
      <%= render 'follow_form' if user_signed_in? %>
    </div>
    <ul class="list-group list-group-flush">
      <% if @user.posts.any? %>
        <li class="list-group-item">
          <span class="badge badge-primary">
            <%= @user.posts.count %>
          </span> Posts
        </li>
      <% end %>
      <li class="list-group-item">
        <%= render 'users/stats' %>
      </li>
    </ul>
  </div>
</div>
<div class="col-md-9">
  <% if @user.posts.any? %>
    <ul class="list-group list-group-flush">
      <%= render @posts %>
    </ul>
    <br>
    <%= will_paginate(
      @posts,
      renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer
    ) %>
  <% end %>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="col-md-3">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= @user.name %></h5>
      <%= render 'follow_form' if user_signed_in? %>
    </div>
    <ul class="list-group list-group-flush">
      <% if @user.posts.any? %>
        <li class="list-group-item">
          <span class="badge badge-primary">
            <%= @user.posts.count %>
          </span> Posts
        </li>
      <% end %>
      <li class="list-group-item">
        <%= render 'users/stats' %>
      </li>
    </ul>
  </div>
</div>
<div class="col-md-9">
  <ul class="list-group list-group-flush">
    <%= render partial: 'user', collection: @users %>
    <%= will_paginate(
      @users,
      renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer
    ) %>
  </ul>
</div>