config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'master#home'

  get 'help', to: 'master#help'
  get 'about', to: 'master#about'
  get 'contact', to: 'master#contact'

  resources :users, only: %i[index show destroy] do
    resources :following, only: :index
    resources :followers, only: :index
  end

  resources :posts do
    resources :comments
  end

  resources :comments do
    resources :comments
  end

  resources :relationships, only: %i[create destroy]
end

app/views/layouts/_header.html.erb
<header class="blog-header py-3">
  <div class="row flex-nowrap justify-content-between align-items-center">
    <div class="col-4 d-flex justify-content-start align-items-center">
      <%= link_to "Write a post", new_post_path,
        class: "btn btn-secondary" %>
      &nbsp;
      <%= link_to "Newest posts", posts_path,
        class: "btn btn-secondary" %>
    </div>
    <div class="col-4 text-center">
      <%= link_to "Awesome Blog", root_path,
        class: "blog-header-logo text-dark" %>
    </div>
    <div class="col-4 d-flex justify-content-end align-items-center">
      <% if user_signed_in? %>
        <%= link_to "Users", users_path, class:"btn btn-primary" %>
        &nbsp;
        <div class="dropdown">
          <button class="btn btn-primary dropdown-toggle"
                  type="button"
                  id="dropdownMenuButton"
                  data-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false">Profile</button>
          <div class="dropdown-menu dropdown-menu-right"
            aria-labelledby="dropdownMenuButton">
            <%= link_to "My posts", user_path(current_user),
              class: "dropdown-item"%>
            <%= link_to "Edit", edit_user_registration_path,
              class: "dropdown-item"%>
            <%= link_to "Logout", destroy_user_session_path,
              class: "dropdown-item", method: "delete" %>
          </div>
        </div>
      <% else %>
        <%= link_to "Login", new_user_session_path,
          class: "btn btn-sm btn-outline-secondary" %>
        &nbsp;
        <%= link_to "Sign up", new_user_registration_path,
            class: "btn btn-sm btn-outline-secondary" %>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <%= full_title yield(:title) %>
    </title>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <div class="container">
      <%= render "layouts/header"%><br>
      <div class="row">
        <% flash.each do |message_type, message| %>
          <% if message_type == "notice"
               message_type = "success"
          elsif message_type == "alert"
            message_type = "danger"
          end %>
          <div class="col-md-12">
            <%= content_tag(
              :div,
              message,
              class: "alert alert-#{message_type}")
            %>
          </div>
        <% end %>
        <%= yield %>
        <%= render "layouts/footer"%>
      </div>
    </div>
  </body>
</html>